### ISSUE TITLE
Stevilo povezav polnega grafa na n tockah

### ISSUE THREAD

**Issue by MitjaR** [MitjaR/Coq_Graph#1]
Kako se uporabi funkcijo edges za dokaz kaksno je stevilo povezav polnega grafa?

**Comment by andrejbauer** [comment]
Ja, ni tako enostavno, se zdi, da je treba pripraviti celo kopico pomožnih lem, da se bo dalo normalno delati s `sum`. Bom premislil, kaj bi bil čim bolj  enostaven setup.

**Comment by MitjaR** [comment]
Aha super. Jaz sem bil včeraj na razgovoru s profesorjem Alex Simpsonom 
in sva že malo poiskusila razčleniti, kako bi se postopno lotil dokazovanja te 
trditve.

Kot korak v tej smeri sem tako tudi včeraj poskusil dokazati naslednjo trditev:

####################
Theorem stevilo_povezav_Kn: (forall n : nat, (edges (K n)) = sum (fun x => sum (fun y => 1) x) (V (K n))).
Proof.
  intro.
  pose edges. (* ali pose (edges (K n))  *)
####################

In sedaj imam problem, ker ne vem kako lahko razpišem izraz (edges (K n)) 
v izraz sum (fun x => sum (fun y => E_decidable (K n) x y) x) (V (K n))).

Sem mislil, da bo [pose] dodal razpisano definicijo te funkcije v okolje,
ampak doda le njen tip (in nerazpisano definicijo?).
Če bi mi namreč to uspelo bi za dokaz zgornje mini trditve potreboval le še 
dokazati, da je za vsaka x,y manjša od V (K n) veljavno E_decidable (K n) x y = true.
